### ISSUE TITLE
Black Diamond PD

### ISSUE THREAD

**Issue by hejokelly** [moxboxwa/wa-pursuit-pdr-data#136]
- [x] PDR sent (7/6/24 - hk)
- [x] Response received by Joann Sloss at jsloss@blackdiamond.wa.gov (6/10/24)
- [x] ETA received (6/28/24)
- [ ] Agency requests clarification (6/18/24)
- [ ] Clarification provided 
- [ ] Data received 
- [ ] Data uploaded
- [ ] Data reviewed (mm 8/8/24)
- [ ] Harmonized file created
- [ ] Report produced

**Comment by moxboxwa** [comment]
Hmmm.  No pursuits?

They walked back their involvement in this one, but I've left it in my data.  The question is whether they signaled the driver to stop, even if they had to turn around in order to chase them:
https://komonews.com/news/local/teen-carjacking-suspects-stolen-hyundai-elantra-black-diamond-police-pursuit-serious-crash-224th-avenue-king-county-harborview-medical-center

And this one is the KCSO in Black Diamond, which led to serious consequences
https://www.seattletimes.com/seattle-news/king-county-sheriff-fires-veteran-detective-over-tactics-that-led-to-2019-fatal-shooting-of-black-diamond-truck-thief/
